### PR TITLE
fix: gh check failing due to missing github organization

### PR DESCRIPTION
**Pull request by sachinsmc**
- **Reword organization label**
- **Added validations for organization name**

### CODE REVIEW

**Comment by sachinsmc** [comment]
https://github.com/commitdev/zero/pull/462

**Comment by sachinsmc** [comment]
https://github.com/commitdev/zero/pull/462

**Comment by sachinsmc** [comment]
@bmonkman please review

**Review by bmonkman — CHANGES_REQUESTED** [review]

**Review by bmonkman — APPROVED** [review]
Thanks for your contribution! 🎉

**Pull request merged**
