### PR TITLE
Ability to override registry

### PR DESCRIPTION
**Pull request by JeanPinzon**
Issue: #469 

- Add `registry.yaml` with the default stacks;
- Add the parameter `registry-file-path` to override the file path on the command `init`. It can be a local or a github path.

### CODE REVIEW

**Comment by JeanPinzon** [comment]
#469

**Comment by JeanPinzon** [comment]
> Thanks for your contribution!! I wonder going forward if we still need to use the `local-module-path` given we can override the entire registry, but we can remove it in a different PR if we find ourselves not using it anymore

I'm not sure if `local-module-path` is just used on `registry`, but if so, it would be interesting to remove it and put the entire URL on the registry file. With this approach, it would be possible to have stacks with templates from different GitHub accounts.

**Comment by davidcheung** [comment]
Yeah i think the registry file "should" cover all the use cases, go-getter allows a pretty wide range of paths
it is a breaking change though (which only affects development on modules) 

@bmonkman what do u think about removing the local-module-path entirely?

**Comment by bmonkman** [comment]
Let's just leave the local module path for now and remove it separately later if we truly end up not using it. I think it's still probably useful as-is when using default values.

**Review by bmonkman — APPROVED** [review]
Looks great, thanks @JeanPinzon!

**Pull request merged**
